// Code generated by "stringer -type=OperatorType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Plus-0]
	_ = x[Minus-1]
	_ = x[Multiply-2]
	_ = x[Divide-3]
	_ = x[Modulo-4]
	_ = x[Equal-5]
	_ = x[NotEqual-6]
	_ = x[Less-7]
	_ = x[LessEqual-8]
	_ = x[Greater-9]
	_ = x[GreaterEqual-10]
	_ = x[And-11]
	_ = x[Or-12]
	_ = x[Not-13]
	_ = x[Assign-14]
	_ = x[PlusAssign-15]
	_ = x[MinusAssign-16]
	_ = x[MultiplyAssign-17]
	_ = x[DivideAssign-18]
}

const _OperatorType_name = "PlusMinusMultiplyDivideModuloEqualNotEqualLessLessEqualGreaterGreaterEqualAndOrNotAssignPlusAssignMinusAssignMultiplyAssignDivideAssign"

var _OperatorType_index = [...]uint8{0, 4, 9, 17, 23, 29, 34, 42, 46, 55, 62, 74, 77, 79, 82, 88, 98, 109, 123, 135}

func (i OperatorType) String() string {
	if i < 0 || i >= OperatorType(len(_OperatorType_index)-1) {
		return "OperatorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperatorType_name[_OperatorType_index[i]:_OperatorType_index[i+1]]
}
